openapi: 3.0.3
info:
  title: PlayMatch API
  description: API for PlayMatch service
  version: 1.0.0
  contact:
    name: PlayMatch Team
    url: https://playmatch.com
    email: support@playmatch.com

servers:
  - url: http://localhost:8081
    description: Local development server
  - url: https://api.playmatch.com
    description: Production server

tags:
  - name: Health
    description: Health check endpoints for service monitoring
  - name: Example
    description: Example API endpoints - Replace with your actual endpoints
  - name: Auth
    description: Authentication and user management endpoints
  - name: PlayerProfile
    description: Core Player Profile management endpoints

paths:
  /api/v1/health/poll:
    get:
      tags:
        - Health
      summary: Long polling health check
      description: Endpoint for gateway to check if service is available for long polling
      operationId: checkLongPollingHealth
      responses:
        '200':
          description: Service is ready for long polling
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is not available for long polling
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/examples:
    get:
      tags:
        - Example
      summary: List examples
      description: Get a list of examples
      operationId: getExamples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

# Auth paths
  /v1/auth/register:
    post:
      tags:
        - Auth
      summary: Create user by email & password
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "201":
          description: User created
          headers:
            X-Request-Id: { schema: { type: string } }
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthUser"
        "400": { $ref: "#/components/responses/BadRequest" }
        "409": { $ref: "#/components/responses/Conflict" }
        "429": { $ref: "#/components/responses/TooManyRequests" }

  /v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login with email & password
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: Login success
          headers:
            X-Request-Id: { schema: { type: string } }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "400": { $ref: "#/components/responses/BadRequest" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "423": { $ref: "#/components/responses/Locked" }
        "429": { $ref: "#/components/responses/TooManyRequests" }

  /v1/auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Start password reset flow
      description: Always returns 202 to avoid user enumeration.
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        "202":
          description: Accepted (email sent if account exists)
          headers:
            X-Request-Id: { schema: { type: string } }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

  /v1/auth/reset-password:
    post:
      tags:
        - Auth
      summary: Complete password reset using token
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        "200":
          description: Password reset successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        "400": { $ref: "#/components/responses/BadRequest" }
        "410": { $ref: "#/components/responses/Gone" }
        "429": { $ref: "#/components/responses/TooManyRequests" }

  # Player Profile paths
  /api/players/profile:
    post:
      tags: [PlayerProfile]
      operationId: createPlayerProfile
      summary: Create player profile (core)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePlayerProfileRequest'
            examples:
              sample:
                summary: Example create request
                value:
                  fullName: "Rahul Mehta"
                  gender: "MALE"
                  mobile: "9876543210"
                  city: "Bengaluru"
                  primaryRole: "BATTER"
                  jerseySize: "L"
                  upiId: "rahulm@okicici"
                  codeOfConductAccepted: true
                  profilePhotoUrl: "https://cdn.playmatch/u/abc.jpg"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerProfileResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '409': { $ref: '#/components/responses/Conflict' }

    put:
      tags: [PlayerProfile]
      operationId: updatePlayerProfile
      summary: Update player profile (partial; only provided fields)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePlayerProfileRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerProfileResponse'
        '400': { $ref: '#/components/responses/BadRequest' }
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '404': { $ref: '#/components/responses/NotFound' }
        '409': { $ref: '#/components/responses/Conflict' }

  /api/players/profile/{userId}:
    get:
      tags: [PlayerProfile]
      operationId: getPlayerProfileByUserId
      summary: Get profile by userId (self read; captain read later)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerProfileResponse'
        '401': { $ref: '#/components/responses/Unauthorized' }
        '403': { $ref: '#/components/responses/Forbidden' }
        '404': { $ref: '#/components/responses/NotFound' }

  /api/players/search:
    get:
      tags: [PlayerProfile]
      operationId: searchPlayers
      summary: Search player summaries by city and/or primaryRole
      security:
        - bearerAuth: []
      parameters:
        - name: city
          in: query
          required: false
          schema: { type: string, maxLength: 80 }
        - name: primaryRole
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/PrimaryRole'
        - name: limit
          in: query
          required: false
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
        - name: offset
          in: query
          required: false
          schema: { type: integer, minimum: 0, default: 0 }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '401': { $ref: '#/components/responses/Unauthorized' }

components:
  schemas:
    Gender:
      type: string
      enum: [ MALE, FEMALE, OTHER ]

    PrimaryRole:
      type: string
      enum: [ BATTER, BOWLER, ALL_ROUNDER, WICKET_KEEPER ]

    JerseySize:
      type: string
      enum: [ S, M, L, XL, XXL ]

    CreatePlayerProfileRequest:
      type: object
      required:
        - fullName
        - gender
        - mobile
        - city
        - primaryRole
        - codeOfConductAccepted
      properties:
        fullName:
          type: string
          maxLength: 80
        gender:
          $ref: '#/components/schemas/Gender'
        mobile:
          type: string
          description: 10-15 digits, numeric only
          pattern: '^[0-9]{10,15}$'
        city:
          type: string
          maxLength: 80
        primaryRole:
          $ref: '#/components/schemas/PrimaryRole'
        jerseySize:
          $ref: '#/components/schemas/JerseySize'
        upiId:
          type: string
          maxLength: 64
          pattern: '^[A-Za-z0-9._-]{2,}@[A-Za-z]{2,}$'
        codeOfConductAccepted:
          type: boolean
          description: Must be true
        profilePhotoUrl:
          type: string
          format: uri
          description: http/https only

    UpdatePlayerProfileRequest:
      type: object
      description: Only provided fields are updated (partial update).
      properties:
        fullName:
          type: string
          maxLength: 80
        gender:
          $ref: '#/components/schemas/Gender'
        mobile:
          type: string
          pattern: '^[0-9]{10,15}$'
        city:
          type: string
          maxLength: 80
        primaryRole:
          $ref: '#/components/schemas/PrimaryRole'
        jerseySize:
          $ref: '#/components/schemas/JerseySize'
        upiId:
          type: string
          maxLength: 64
          pattern: '^[A-Za-z0-9._-]{2,}@[A-Za-z]{2,}$'
        codeOfConductAccepted:
          type: boolean
        profilePhotoUrl:
          type: string
          format: uri

    PlayerProfileResponse:
      type: object
      required:
        - id
        - userId
        - fullName
        - gender
        - mobile
        - city
        - primaryRole
        - jerseySize
        - upiId
        - codeOfConductAccepted
        - createdAt
        - updatedAt
      properties:
        id: { type: string, format: long }
        userId: { type: string, format: uuid }
        fullName: { type: string }
        gender: { $ref: '#/components/schemas/Gender' }
        mobile: { type: string }
        city: { type: string }
        primaryRole: { $ref: '#/components/schemas/PrimaryRole' }
        jerseySize: { $ref: '#/components/schemas/JerseySize' }
        upiId: { type: string }
        codeOfConductAccepted: { type: boolean }
        profilePhotoUrl: { type: string, format: uri, nullable: true }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }

    PlayerSummary:
      type: object
      properties:
        userId: { type: string, format: uuid }
        fullName: { type: string }
        city: { type: string }
        primaryRole: { $ref: '#/components/schemas/PrimaryRole' }
        jerseySize: { $ref: '#/components/schemas/JerseySize' }
        profilePhotoUrl: { type: string, format: uri, nullable: true }

    SearchResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/PlayerSummary'


    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [UP, DOWN]
          example: "UP"
        timestamp:
          type: string
          format: date-time
          example: "2025-09-27T12:00:00Z"
        message:
          type: string
          example: "Service is ready for long polling"
      required:
        - status
        - timestamp

    ExampleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Example Name"
        description:
          type: string
          example: "Example Description"
      required:
        - id
        - name

    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - status
        - error
        - message
        - path

    RegisterRequest:
      type: object
      required: [name, gender, email, password, reEnterPassword]
      properties:
        name: { type: string, minLength: 1, maxLength: 120 }
        gender:
          type: string
          enum: [male, female, other, prefer_not_to_say]
        email: { type: string, format: email, maxLength: 254 }
        password: { type: string, minLength: 8, maxLength: 128 }
        reEnterPassword: { type: string, minLength: 8, maxLength: 128 }

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email: { type: string, format: email }
        password: { type: string }

    LoginResponse:
      type: object
      required: [accessToken, tokenType, expiresIn, user]
      properties:
        accessToken: { type: string }
        tokenType: { type: string, example: Bearer }
        expiresIn: { type: integer, example: 3600 }
        refreshToken: { type: string, nullable: true }
        user: { $ref: "#/components/schemas/AuthUser" }

    ForgotPasswordRequest:
      type: object
      required: [email]
      properties:
        email: { type: string, format: email }

    ResetPasswordRequest:
      type: object
      required: [token, password, reEnterPassword]
      properties:
        token: { type: string }
        password: { type: string, minLength: 8, maxLength: 128 }
        reEnterPassword: { type: string, minLength: 8, maxLength: 128 }

    MessageResponse:
      type: object
      properties:
        message: { type: string }

    AuthUser:
      type: object
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        gender:
          type: string
          enum: [male, female, other, prefer_not_to_say]
        email: { type: string, format: email }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
        lastLoginAt: { type: string, format: date-time, nullable: true }

    Problem:
      type: object
      required: [type, title, status]
      properties:
        type: { type: string, example: "https://api.example.com/errors/validation" }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
        instance: { type: string }

  responses:
    BadRequest:
      description: Validation or malformed request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Problem"
    Unauthorized:
      description: Invalid credentials
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
    Forbidden:
      description: Forbidden - Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found - Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Email already in use
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
    Locked:
      description: Account temporarily locked due to too many attempts
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
    Gone:
      description: Token expired or already used
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
    TooManyRequests:
      description: Rate limit exceeded
      headers:
        Retry-After: { schema: { type: integer } }
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
