openapi: 3.0.3
info:
  title: PlayMatch API
  description: API for PlayMatch service
  version: 1.0.0
  contact:
    name: PlayMatch Team
    url: https://playmatch.com
    email: support@playmatch.com

servers:
  - url: http://localhost:8081
    description: Local development server
  - url: https://api.playmatch.com
    description: Production server

tags:
  - name: Health
    description: Health check endpoints for service monitoring
  - name: Example
    description: Example API endpoints - Replace with your actual endpoints
  - name: Auth
    description: Authentication and user management endpoints

paths:
  /api/v1/health/poll:
    get:
      tags:
        - Health
      summary: Long polling health check
      description: Endpoint for gateway to check if service is available for long polling
      operationId: checkLongPollingHealth
      responses:
        '200':
          description: Service is ready for long polling
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is not available for long polling
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/examples:
    get:
      tags:
        - Example
      summary: List examples
      description: Get a list of examples
      operationId: getExamples
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

# Auth paths
  /v1/auth/register:
    post:
      tags:
        - Auth
      summary: Create user by email & password
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "201":
          description: User created
          headers:
            X-Request-Id: { schema: { type: string } }
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthUser"
        "400": { $ref: "#/components/responses/BadRequest" }
        "409": { $ref: "#/components/responses/Conflict" }
        "429": { $ref: "#/components/responses/TooManyRequests" }

  /v1/auth/login:
    post:
      tags:
        - Auth
      summary: Login with email & password
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: Login success
          headers:
            X-Request-Id: { schema: { type: string } }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "400": { $ref: "#/components/responses/BadRequest" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "423": { $ref: "#/components/responses/Locked" }
        "429": { $ref: "#/components/responses/TooManyRequests" }

  /v1/auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Start password reset flow
      description: Always returns 202 to avoid user enumeration.
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        "202":
          description: Accepted (email sent if account exists)
          headers:
            X-Request-Id: { schema: { type: string } }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

  /v1/auth/reset-password:
    post:
      tags:
        - Auth
      summary: Complete password reset using token
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        "200":
          description: Password reset successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        "400": { $ref: "#/components/responses/BadRequest" }
        "410": { $ref: "#/components/responses/Gone" }
        "429": { $ref: "#/components/responses/TooManyRequests" }

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [UP, DOWN]
          example: "UP"
        timestamp:
          type: string
          format: date-time
          example: "2025-09-27T12:00:00Z"
        message:
          type: string
          example: "Service is ready for long polling"
      required:
        - status
        - timestamp

    ExampleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Example Name"
        description:
          type: string
          example: "Example Description"
      required:
        - id
        - name

    Error:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string
        path:
          type: string
      required:
        - status
        - error
        - message
        - path

    RegisterRequest:
      type: object
      required: [name, gender, email, password, reEnterPassword]
      properties:
        name: { type: string, minLength: 1, maxLength: 120 }
        gender:
          type: string
          enum: [male, female, other, prefer_not_to_say]
        email: { type: string, format: email, maxLength: 254 }
        password: { type: string, minLength: 8, maxLength: 128 }
        reEnterPassword: { type: string, minLength: 8, maxLength: 128 }

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email: { type: string, format: email }
        password: { type: string }

    LoginResponse:
      type: object
      required: [accessToken, tokenType, expiresIn, user]
      properties:
        accessToken: { type: string }
        tokenType: { type: string, example: Bearer }
        expiresIn: { type: integer, example: 3600 }
        refreshToken: { type: string, nullable: true }
        user: { $ref: "#/components/schemas/AuthUser" }

    ForgotPasswordRequest:
      type: object
      required: [email]
      properties:
        email: { type: string, format: email }

    ResetPasswordRequest:
      type: object
      required: [token, password, reEnterPassword]
      properties:
        token: { type: string }
        password: { type: string, minLength: 8, maxLength: 128 }
        reEnterPassword: { type: string, minLength: 8, maxLength: 128 }

    MessageResponse:
      type: object
      properties:
        message: { type: string }

    AuthUser:
      type: object
      properties:
        id: { type: string, format: uuid }
        name: { type: string }
        gender:
          type: string
          enum: [male, female, other, prefer_not_to_say]
        email: { type: string, format: email }
        createdAt: { type: string, format: date-time }
        updatedAt: { type: string, format: date-time }
        lastLoginAt: { type: string, format: date-time, nullable: true }

    Problem:
      type: object
      required: [type, title, status]
      properties:
        type: { type: string, example: "https://api.example.com/errors/validation" }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
        instance: { type: string }

  responses:
    BadRequest:
      description: Validation or malformed request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Problem"
    Unauthorized:
      description: Invalid credentials
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
    Forbidden:
      description: Forbidden - Insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not Found - Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Conflict:
      description: Email already in use
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
    Locked:
      description: Account temporarily locked due to too many attempts
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
    Gone:
      description: Token expired or already used
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
    TooManyRequests:
      description: Rate limit exceeded
      headers:
        Retry-After: { schema: { type: integer } }
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Problem" }
